### ISSUE TITLE
Please  suport  Compute shaders  GPU Compute 

### ISSUE THREAD

**Issue by longde123** [saharan/HGSL#4]

**Comment by saharan** [comment]
I'm not planning to support compute shaders in HGSL, since the main purpose of HGSL is to easily write shaders for WebGL 2.0 and unfortunately Khronos Group has made a decision that [they won't support compute shaders](https://registry.khronos.org/webgl/specs/latest/2.0-compute/) in future WebGL versions.

I'm waiting for the WebGPU era but for me it seems it will take like a decade for WebGPU to take over WebGL.
